# config/fontcustom.yml

font_name: mysalon
css_selector: .mysalon-{{glyph}}
preprocessor_path: ""
autowidth: false
no_hash: true
force: false
debug: true
quiet: false

input:
  vectors: app/assets/icons

output:
  fonts: app/assets/fonts
  css: app/assets/stylesheets

templates:
 - scss
